### ISSUE TITLE
Custom reverse proxy headers not generated

### ISSUE THREAD

**Issue by MrHash** [blacklabelops/nginx#11]
Looking at this line: https://github.com/blacklabelops/nginx/blob/master/imagescripts/reverse_proxy.sh#L91 it looks like there is no `${i}` counter so no proxy headers are generated!

**Comment by blacklabelops** [comment]
Thank you for reporting this problem, I will check the feature shortly.

**Comment by MrHash** [comment]
Example config is where `${HOST_NAME}` is an environment variable `honeylex.dev`. Tried the quoted technique as given in the docs as well.

```
    environment:
      NGINX_REDIRECT_PORT80: "true"
      SERVER1SERVER_NAME: ${HOST_NAME}
      SERVER1HTTP_ENABLED: "false"
      SERVER1HTTPS_ENABLED: "true"
      SERVER1REVERSE_PROXY_LOCATION1: /
      SERVER1REVERSE_PROXY_PASS1: http://nginx:8000
      SERVER1PROXY_APPLICATION: custom
      SERVER1REVERSE_PROXY_HEADER1FIELD1: X-Forwarded-Host ${HOST_NAME}
```
