### ISSUE TITLE
Question: Is there a dynamic solution for same host port-forwarding?

### ISSUE THREAD

**Issue by mattmeye** [blacklabelops/nginx#15]
hello,

i use your proxy template for simple port-forwarding, e.g. docker-elk (port 6501 for kibana) on the same host

```
version: '2'
services:
  nginx-proxy:
    image: blacklabelops/nginx
    ports:
      - "80:80"
    environment:
      - "SERVER1REVERSE_PROXY_LOCATION1=/"
      - "SERVER1REVERSE_PROXY_PASS1=http://HOSTIP:5601"
```

I have to replace HOSTIP with the mashine ip. Is there a dynamic solution?
