### ISSUE TITLE
URI with White Spaces (%20) fails

### ISSUE THREAD

**Issue by paalkr** [blacklabelops/nginx#33]
Hi

I'm using your nginx reverse proxy image, and for most it works perfect. Thanks!

For on of my services
`REVERSE_PROXY_BACKEND='$backend$uri$is_args$args'`
does not work due to white spaces in the URI.

This is the entry from the proxy log
`[22/Aug/2017:21:56:54 +0000] "GET /arcgis/rest/services/Geosok/GeosokRute3/NAServer/Closest%20Facility HTTP/1.1" 400 0 "<HTTP ref>" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0"`
And I don't see any trace of the request at my backend request logs, it seems like the request isn't ever sent to the backend at all.

Requests without white spaces works as expected, like the one below
`[22/Aug/2017:22:05:32 +0000] "GET /arcgis/rest/services/Geosok/GeosokRute3/NAServer/Route HTTP/1.1" 304 0 "<HTTP ref>" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0"`

If I query the backend directly bypassing the proxy the requests succeeds.
Changing
`REVERSE_PROXY_BACKEND='$backend$request_uri'`
will make the request work, but unfortunately it breaks some other features of my backend

This is a snippet of my config (Kubernetes deployment)
```
        env:       
        - name: SERVER1REVERSE_PROXY_LOCATION1
          value: /
        - name: SERVER1REVERSE_PROXY_PASS1
          value: https://my.backend.server
        - name: SERVER1HTTPS_ENABLED
          value: 'true'
        - name: SERVER1HTTP_ENABLED
          value: 'false'          
        - name: SERVER1CERTIFICATE_DNAME
          value: '/CN=xx/OU=xx/O=xx.xx/L=xx/C=xx'
```

Any suggestions?
